project:
  output-dir: _output
  type: website
  title: "Offsets"
  resources:
    - data/cmo_statements.csv

website:
  title: "Offsets"
  sidebar: 
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - text: "Home"
        href: index.qmd
      - text: "Report"
        href: report.qmd
      - text: "CMO Explorer"
        href: explorer.qmd
format:
  html:
    html-math-method: katex

toc: true
number-sections: true
bibliography: references/offsets.bib  
