project:
  output-dir: _output
  execute-dir: project
  type: website
  title: "Offsets"
  resources:
    - data/cmo_statements.csv

website:
  title: "Offsets"
  sidebar: 
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - text: "Home"
        href: index.qmd
      - text: "Report"
        href: pages/report.qmd
      - text: "CMO Explorer"
        href: pages/explorer.qmd
      - section: "Methods"
        contents:
        - analysis/normalise-tags.qmd
        - analysis/tag-dendrograms.qmd
      - section: "Synthesis"
        contents:
        - auto: "synthesis/**.qmd"
format:
  html:
    html-math-method: katex

toc: true
number-sections: true
bibliography: references/offsets.bib  
