project:
  output-dir: _output
  execute-dir: project
  type: website
  title: "Offsets"

website:
  title: "Offsets"
  sidebar: 
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - text: "Home"
        href: index.qmd
      - section: "Analysis"
        contents:
          - auto: "analysis/*.qmd"

format:
  html:
    html-math-method: katex

toc: true
number-sections: true
bibliography: references/offsets.bib
